apiVersion: apps/v1
kind: Deployment
metadata:
  name: canaryv1
spec:
  replicas: {{ .values.canaryv1replicas }}
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
      - name: canaryv1
        image: seun007/booksiread:{{ .values.canaryv2image.tag }}
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 3000
