apiVersion: apps/v1
kind: Deployment
metadata:
  name: canaryv2
spec:
  replicas: {{ .Values.canaryv2replicas }}
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
      - name: canaryv2
        image: seun007/booksiread:{{ .Values.canaryv2image.tag }}  
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 3000
