name: "Deployment Workflow"
on: 
    push:
        branches:
            - tests

jobs: 
    simple_deploy:
        runs-on: ubuntu-latest
        steps:
        - name: "Checkouts out"
          uses: actions/checkout@v4
        
        - name: "Build the image"
          run: |
                sudo docker build -t theoafactor/bik_latest:123 frontend/
            
        # - name: "Push the image to DockerHub"
        #   run: |
        #         sudo docker push theoafactor/bik_latest:123

            

