name: Deployment Workflow
on:
  push:
    branches:
      - development

jobs:
  Development:
    runs-on: ubuntu-latest
    steps:
      - name: "Greetings"
        run: |
          echo "--- Greetings ----"
      
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Create version number"
        run: |
          echo "APP_VERSION=${RANDOM}" >> $GITHUB_ENV
        

          echo ${{ env.APP_VERSION }}

      - name: checks out the repository
        uses: actions/checkout@v3
                     

      - name: "Logs into docker"
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}  
      
      - name: "Build the image"
        run: |
          echo ${{ env.APP_VERSION }}
          sudo docker build -t seun007/booksiread:${{ env.APP_VERSION }} frontend/
      - name: "Push the image to docker hub" 
        run: |
            docker push seun007/booksiread:${{ env.APP_VERSION }}

            
      - name: "Setup AWS"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "us-east-1"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           

      - name: "Get kubectl"
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.19.3"
        id: install-kubectl

      - name: "Connect to the cluster"
        run: |
          aws eks update-kubeconfig --name Pcluster 
      
      - name: "install Helm"
        uses: azure/setup-helm@v4.2.0
        id: install-helm  
      
      - name: "Update Install Chart"
        run: |
          helm upgrade --install bik bik -f bik/values.yaml --set image.tag=${{ env.APP_VERSION }}   
          

         